### ISSUE TITLE
Formatting in Table Of Contents makes it hard to recognize subheadings

### ISSUE THREAD

**Issue by FelixBrendel** [bphenriques/explorer-hugo-theme#11]
Right now nested headings look like the following in the Table Of Contents:
![image](https://user-images.githubusercontent.com/5005975/170882702-e2365e0a-81e1-4a44-aeda-18be0a0d5392.png)

I would like to propose the following css to indent subheadings:
```css
#TableOfContents li {
    margin-top: 0.4rem;
    margin-bottom: 0.4rem;
}

#TableOfContents li li {
    margin-left: 1em;
}
```

With the applied styles:
![image](https://user-images.githubusercontent.com/5005975/170882650-14288d26-c13e-49f1-b44b-9c7066cacd34.png)

I would be happy for any feedback on this!
